"""Init_tables

Revision ID: 9b65b0abb84e
Revises: 
Create Date: 2022-05-15 00:56:14.236519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b65b0abb84e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("song_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "lists",
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("list_name", sa.String(), nullable=False),
        sa.Column(
            "list_type",
            sa.Enum("default", "artist", "user", name="listenum"),
            server_default="user",
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("list_id"),
    )
    op.create_table(
        "binds",
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.list_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.song_id"],
        ),
        sa.PrimaryKeyConstraint("list_id", "song_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binds")
    op.drop_table("lists")
    op.drop_table("users")
    op.drop_table("songs")
    # ### end Alembic commands ###
