"""empty message

Revision ID: 10ceda8421aa
Revises: 
Create Date: 2022-04-21 00:41:50.572888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10ceda8421aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("song_name", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("song_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "lists",
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("list_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("list_id"),
    )
    op.create_table(
        "binds",
        sa.Column("bind_id", sa.Integer(), nullable=False),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["lists.list_id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.song_id"],
        ),
        sa.PrimaryKeyConstraint("bind_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("binds")
    op.drop_table("lists")
    op.drop_table("users")
    op.drop_table("songs")
    # ### end Alembic commands ###
