---
name: Check files formatting

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]

jobs:
  check-yaml:
    name: Check yaml formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: make init

      - name: Run check
        run: make check-yamllint

  check-python:
    name: Check python formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: make init

      - name: Run check
        run: make check-black
