name: Makefile CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: make init
      
    - name: Run check
      run: make check

